In [2]:
from math import radians, cos, sin, asin, sqrt

import numpy as np

# def haversine(df.loc[0,'longitude'], df.loc[0,'latitude'],df.loc[i,'longitude'], df.loc[i,'latitude'])
 
def haversine(lon1, lat1, lon2, lat2): # 经度1，纬度1，经度2，纬度2 （十进制度数）
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # 将十进制度数转化为弧度
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    

#     vector1 = np.array([lon1, lat1]).reshape(2, 1)

#     vector2 = np.array([lon2, lat2]).reshape(2, 1)

    # haversine公式
    
#     dlon = vector2[0,0]-vector1[0,0]
        
#     dlat = vector2[1,0]-vector1[1,0]
        
    dlon = lon2 - lon1 
        
    dlat = lat2 - lat1 




    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # 地球平均半径，单位为公里
    
    b = 0
    
    return round(c * r,3)


In [3]:
import pandas as pd

csv_file = "C:/Users/Big data/Desktop/report/north_place_google_api_area_v1.csv"
csv_data = pd.read_csv(csv_file, low_memory = False)#防止弹出警告
df = pd.DataFrame(csv_data)

In [4]:
df

url place_name area  \
0     https://tour.ntpc.gov.tw/zh-tw/Attraction/Deta...       九份老街  新北市   
1     https://tour.ntpc.gov.tw/zh-tw/Attraction/Deta...     野柳地質公園  新北市   
2     https://tour.ntpc.gov.tw/zh-tw/Attraction/Deta...    三貂嶺瀑布步道  新北市   
3     https://tour.ntpc.gov.tw/zh-tw/Attraction/Deta...        新月橋  新北市   
4     https://tour.ntpc.gov.tw/zh-tw/Attraction/Deta...        不厭亭  新北市   
...                                                 ...        ...  ...   
1918  https://tour.klcg.gov.tw/zh/attractions/temple...        奠濟宮  基隆市   
1919  https://tour.klcg.gov.tw/zh/attractions/temple...      暖暖安德宮  基隆市   
1920  https://tour.klcg.gov.tw/zh/attractions/temple...   暖暖雙生土地公廟  基隆市   
1921  https://tour.klcg.gov.tw/zh/attractions/temple...     獅球嶺平安宮  基隆市   
1922  https://tour.klcg.gov.tw/zh/attractions/temple...        慶安宮  基隆市   

                      address   longitude   latitude  
0     新北市瑞芳區基山街、輕便路、汽車路、豎崎路一帶  121.845183  25.109870  
1          新北市萬里區野柳村港東路167-1號  121.690466  25.206397  
2              新北市瑞芳區碩仁里魚寮路1號  121.822559  25.065544  
3                  新北市板橋區環河道路  121.448465  24.996910  
4                  新北市雙溪區瑞雙公路  121.849541  25.066288  
...                       ...         ...        ...  
1918           基隆市仁愛區仁三路27之2號  121.743332  25.128220  
1919             基隆市暖暖區暖暖街63號  121.738587  25.102091  
1920        基隆市暖暖區水源路36巷37-1號  121.733900  25.095700  
1921       基隆市仁愛區獅球路48巷174-1號  121.734296  25.122720  
1922              基隆市仁愛區忠二路1號  121.740609  25.129628  

[1923 rows x 6 columns]

In [4]:
df.loc[0,'longitude']

121.84518270000001

In [6]:
df.loc[0,'latitude']

25.109869500000002

In [7]:
df.loc[1,'longitude']

121.6904658

In [8]:
df.loc[1,'latitude']

25.206397199999998

In [5]:
place_list = df['place_name'].tolist()#從dataframe提取景點list供後續查長度

產生row，每個row代表與其他景點的距離

In [6]:
for n in range(1923):
    
    place_list[n] = []
    
#     print(place_list[a])

# for n in range(1923):
    
#     if n < i:

    lon1=df.loc[n,'longitude']

    lat1=df.loc[n,'latitude']

    for i in range(1923):

        lon2=df.loc[i,'longitude']

        lat2=df.loc[i,'latitude']

        place_list[n].append(haversine(lon1, lat1, lon2, lat2))       

    print(np.array(place_list[n]))



[ 0.    18.913  5.43  ... 11.316 11.255 10.755]
[18.913  0.    20.545 ... 13.062 10.297  9.916]
[ 5.43  20.545  0.    ...  9.538 10.928 10.903]
[41.89  33.711 38.455 ... 30.781 32.01  32.919]
[ 4.866 22.342  2.719 ... 12.097 13.193 13.036]
[ 0.136 19.048  5.41  ... 11.417 11.376 10.881]
[18.441  1.112 19.823 ... 12.087  9.388  9.073]
[40.528 40.861 35.562 ... 31.919 34.436 35.426]
[41.37  25.509 40.291 ... 30.776 30.128 30.626]
[51.717 44.27  47.892 ... 40.839 42.281 43.215]
[26.144 24.005 22.109 ... 15.918 18.059 19.055]
[ 1.262 20.007  5.999 ... 12.553 12.515 12.006]
[41.778 25.826 40.724 ... 31.206 30.538 31.03 ]
[ 2.071 19.477  7.385 ... 13.074 12.689 12.08 ]
[ 3.108 19.143  2.435 ...  9.472 10.188  9.948]
[40.135 31.623 36.836 ... 28.964 30.104 31.002]
[51.77  44.284 47.953 ... 40.886 42.321 43.254]
[48.084 39.702 44.541 ... 37.013 38.26  39.169]
[41.35  25.558 40.242 ... 30.732 30.104 30.608]
[40.717 30.614 37.801 ... 29.422 30.235 31.079]
[22.814 24.167 18.298 ... 13.801 16.438 

[28.899 33.982 23.61  ... 22.451 25.369 26.27 ]
[39.128 25.785 37.212 ... 27.981 27.987 28.665]
[23.428  5.006 24.407 ... 15.869 13.585 13.506]
[35.279 28.425 31.773 ... 24.261 25.663 26.6  ]
[35.822 31.06  31.836 ... 25.258 27.053 28.029]
[28.017  9.132 29.276 ... 20.818 18.511 18.392]
[22.626 22.572 18.422 ... 12.922 15.372 16.362]
[28.915 10.054 30.092 ... 21.532 19.286 19.196]
[46.648 41.219 42.503 ... 36.152 37.908 38.879]
[38.226 31.887 34.49  ... 27.365 28.903 29.854]
[40.68  40.761 35.744 ... 31.963 34.454 35.445]
[46.049 33.265 43.741 ... 34.78  35.054 35.784]
[41.691 30.347 39.082 ... 30.377 30.926 31.719]
[43.07  32.368 40.24  ... 31.761 32.478 33.301]
[37.833 26.114 35.473 ... 26.544 26.927 27.691]
[37.299 30.488 33.702 ... 26.331 27.769 28.71 ]
[23.471  4.569 24.9   ... 16.811 14.301 14.082]
[41.63  26.227 40.358 ... 30.88  30.375 30.914]
[22.745 24.175 18.218 ... 13.765 16.412 17.384]
[22.711 24.86  18.047 ... 14.114 16.839 17.799]
[35.556 28.221 32.15  ... 24.469 25.78  

[26.833  8.683 27.446 ... 18.49  16.523 16.584]
[15.543 20.554 11.003 ...  8.044 11.034 11.874]
[40.196 30.363 37.228 ... 28.913 29.776 30.629]
[ 0.521 18.853  4.934 ... 10.922 10.967 10.503]
[41.129 33.119 37.677 ... 30.034 31.287 32.201]
[39.203 23.998 37.933 ... 28.451 27.948 28.492]
[40.097 40.01  35.194 ... 31.291 33.762 34.754]
[38.266 26.608 35.872 ... 26.972 27.379 28.148]
[35.63  31.734 31.476 ... 25.296 27.234 28.22 ]
[37.377 18.474 38.554 ... 29.823 27.702 27.652]
[14.589  8.051 14.301 ...  5.357  3.434  3.837]
[38.026 20.006 38.144 ... 28.781 27.285 27.505]
[51.599 44.318 47.741 ... 40.752 42.222 43.16 ]
[ 0.115 18.872  5.331 ... 11.213 11.17  10.676]
[ 0.932 19.399  6.172 ... 12.209 12.052 11.513]
[11.196 30.044 10.871 ... 20.374 21.409 21.176]
[37.921 29.041 34.793 ... 26.688 27.719 28.602]
[41.684 25.787 40.61  ... 31.095 30.442 30.938]
[18.668 32.408 13.665 ... 19.454 22.111 22.554]
[32.962 30.716 28.59  ... 23.057 25.234 26.23 ]
[39.533 30.991 36.262 ... 28.352 29.478 

[22.892 24.154 18.388 ... 13.84  16.466 17.441]
[14.245 32.983 13.239 ... 22.767 24.046 23.887]
[44.016 28.352 42.782 ... 33.299 32.763 33.289]
[21.376 16.891 18.422 ... 10.215 11.7   12.666]
[45.798 38.711 42.012 ... 34.919 36.388 37.327]
[12.557 18.926  8.248 ...  5.917  8.884  9.601]
[44.461 28.2   43.472 ... 33.949 33.235 33.708]
[19.182 15.542 16.376 ...  7.995  9.546 10.523]
[18.781 16.721 15.603 ...  7.892  9.87  10.866]
[15.513 20.54  10.974 ...  8.023 11.014 11.853]
[10.261 29.169 10.572 ... 19.959 20.813 20.522]
[40.27  40.542 35.316 ... 31.627 34.137 35.127]
[ 9.655 19.036  5.175 ...  6.229  8.74   9.187]
[34.326 30.353 30.236 ... 23.926 25.841 26.826]
[26.538 34.417 21.116 ... 21.974 24.978 25.78 ]
[35.997 33.371 31.592 ... 26.075 28.211 29.206]
[44.544 33.983 41.633 ... 33.244 34.011 34.843]
[ 0.268 19.164  5.298 ... 11.438 11.436 10.951]
[13.206 20.429  8.482 ...  7.419 10.379 11.08 ]
[36.652 30.253 32.986 ... 25.745 27.254 28.202]
[23.326  9.334 22.749 ... 13.27  12.144 

[ 3.536 16.014  5.257 ...  7.871  7.735  7.283]
[ 2.115 19.588  7.396 ... 13.16  12.789 12.183]
[42.36  30.527 39.871 ... 31.056 31.502 32.273]
[36.633 34.704 32.087 ... 26.979 29.216 30.213]
[14.909 17.243 11.291 ...  5.313  8.143  9.068]
[15.585 33.741 13.336 ... 22.588 24.253 24.236]
[43.07  35.785 39.396 ... 32.116 33.527 34.461]
[22.836 24.093 18.338 ... 13.776 16.402 17.377]
[52.49  44.031 48.878 ... 41.446 42.708 43.618]
[35.664 28.233 32.277 ... 24.566 25.858 26.781]
[51.221 43.792 47.401 ... 40.342 41.784 42.718]
[ 1.354 20.069  6.08  ... 12.651 12.605 12.093]
[36.5   26.086 33.831 ... 25.184 25.846 26.667]
[41.034 41.432 36.052 ... 32.468 34.992 35.981]
[35.95  25.712 33.259 ... 24.636 25.325 26.152]
[51.581 44.114 47.763 ... 40.698 42.135 43.069]
[38.789 35.754 34.378 ... 28.817 30.905 31.898]
[43.793 27.386 42.886 ... 33.354 32.581 33.038]
[36.158 24.646 33.812 ... 24.869 25.261 26.029]
[ 0.402 18.854  5.051 ... 11.003 11.022 10.549]
[48.599 40.042 45.085 ... 37.508 38.725 

[44.449 36.068 40.991 ... 33.342 34.558 35.464]
[35.157 27.676 31.804 ... 24.042 25.316 26.237]
[47.921 39.612 44.364 ... 36.86  38.119 39.03 ]
[23.209 28.7   18.004 ... 16.747 19.702 20.578]
[36.815 30.577 33.107 ... 25.943 27.484 28.436]
[30.969 12.064 32.429 ... 24.076 21.726 21.572]
[35.142 16.576 35.774 ... 26.688 24.846 24.93 ]
[41.582 34.482 37.908 ... 30.639 32.07  33.007]
[51.368 48.034 46.775 ... 41.564 43.648 44.64 ]
[47.233 34.588 44.852 ... 35.95  36.273 37.013]
[48.239 41.731 44.279 ... 37.512 39.097 40.05 ]
[48.117 39.537 44.618 ... 37.018 38.228 39.131]
[40.542 31.318 37.405 ... 29.303 30.302 31.178]
[53.93  44.36  50.559 ... 42.75  43.808 44.685]
[48.307 39.826 44.781 ... 37.224 38.453 39.36 ]
[51.394 44.256 47.509 ... 40.573 42.067 43.008]
[25.74  30.914 20.502 ... 19.204 22.135 23.028]
[19.929 28.806 14.518 ... 15.953 18.942 19.668]
[51.919 46.385 47.702 ... 41.473 43.235 44.205]
[37.395 18.909 37.898 ... 28.717 26.975 27.097]
[25.693  6.782 27.111 ... 18.898 16.458 

[31.783 22.432 29.079 ... 20.473 21.252 22.102]
[29.76  18.419 27.741 ... 18.545 18.74  19.483]
[29.116 23.265 25.712 ... 18.097 19.581 20.533]
[12.445 20.137  7.739 ...  7.082  9.992 10.649]
[29.894 26.058 25.984 ... 19.358 21.249 22.234]
[32.393 24.967 29.165 ... 21.232 22.462 23.38 ]
[29.446 23.051 26.15  ... 18.35  19.727 20.667]
[29.199 22.696 25.946 ... 18.081 19.427 20.364]
[30.87  20.989 28.366 ... 19.556 20.174 20.997]
[31.302 21.772 28.675 ... 19.987 20.706 21.547]
[32.635 24.291 29.62  ... 21.385 22.42  23.31 ]
[34.245 20.107 32.805 ... 23.357 23.004 23.601]
[29.499 22.985 26.228 ... 18.388 19.74  20.677]
[33.624 25.553 30.489 ... 22.413 23.533 24.434]
[32.06  20.744 29.876 ... 20.799 21.106 21.866]
[35.709 26.9   32.657 ... 24.459 25.464 26.345]
[35.385 26.672 32.323 ... 24.139 25.157 26.041]
[34.554 24.859 31.786 ... 23.247 24.027 24.872]
[27.686 14.758 26.304 ... 16.82  16.453 17.071]
[25.964 15.961 23.91  ... 14.722 15.032 15.814]
[30.444 23.865 27.126 ... 19.35  20.713 

[31.715 24.688 28.429 ... 20.59  21.889 22.817]
[32.726 25.498 29.432 ... 21.597 22.876 23.8  ]
[33.155 28.182 29.324 ... 22.456 24.185 25.157]
[29.75  20.287 27.213 ... 18.435 19.109 19.946]
[33.444 25.712 30.234 ... 22.266 23.454 24.365]
[38.684 24.966 36.907 ... 27.603 27.5   28.151]
[35.632 26.835 32.58  ... 24.382 25.387 26.269]
[33.589 23.741 30.911 ... 22.275 22.993 23.829]
[33.73  24.8   30.805 ... 22.452 23.384 24.256]
[34.4   25.346 31.473 ... 23.12  24.042 24.911]
[35.425 27.573 32.148 ... 24.267 25.469 26.38 ]
[38.439 24.897 36.614 ... 27.333 27.27  27.932]
[31.806 19.317 29.983 ... 20.682 20.674 21.364]
[34.387 24.628 31.644 ... 23.077 23.838 24.68 ]
[31.705 18.456 30.12  ... 20.714 20.497 21.137]
[35.703 26.874 32.656 ... 24.451 25.451 26.332]
[32.952 21.247 30.827 ... 21.711 21.953 22.696]
[32.947 22.675 30.42  ... 21.633 22.23  23.045]
[31.878 20.444 29.74  ... 20.63  20.899 21.651]
[31.384 19.642 29.367 ... 20.175 20.344 21.076]
[31.127 27.547 27.098 ... 20.717 22.668 

[34.189 25.18  31.26  ... 22.91  23.836 24.707]
[32.52  20.286 30.575 ... 21.343 21.432 22.143]
[34.42  26.236 31.272 ... 23.21  24.322 25.221]
[33.356 25.873 30.09  ... 22.207 23.446 24.364]
[33.49  24.259 30.655 ... 22.194 23.051 23.912]
[28.878 22.216 25.687 ... 17.729 19.031 19.963]
[28.517 19.087 26.067 ... 17.204 17.829 18.66 ]
[31.21  23.6   28.096 ... 20.004 21.164 22.074]
[33.222 26.087 29.88  ... 22.117 23.426 24.353]
[34.493 26.346 31.332 ... 23.288 24.409 25.31 ]
[29.861 18.514 27.836 ... 18.644 18.843 19.586]
[32.908 25.762 29.584 ... 21.793 23.093 24.02 ]
[33.215 24.313 30.311 ... 21.934 22.859 23.731]
[59.207 56.097 54.494 ... 49.587 51.714 52.707]
[64.736 59.081 60.392 ... 54.393 56.172 57.142]
[61.507 54.072 57.542 ... 50.717 52.202 53.14 ]
[60.518 46.008 58.525 ... 49.368 49.351 50.001]
[63.1   57.01  58.852 ... 52.631 54.339 55.302]
[59.732 55.418 55.204 ... 49.726 51.691 52.676]
[62.107 56.144 57.844 ... 51.661 53.387 54.351]
[66.706 66.202 61.614 ... 58.169 60.606 

[62.385 52.995 58.849 ... 51.27  52.407 53.295]
[64.448 54.901 60.925 ... 53.321 54.437 55.321]
[59.721 56.366 55.04  ... 50.023 52.119 53.111]
[56.817 44.412 54.174 ... 45.505 45.98  46.746]
[48.169 36.111 45.589 ... 36.859 37.333 38.105]
[61.543 54.052 57.589 ... 50.742 52.218 53.154]
[51.882 41.435 48.773 ... 40.614 41.48  42.324]
[68.464 61.654 64.304 ... 57.86  59.467 60.418]
[79.225 65.935 76.615 ... 67.92  68.303 69.04 ]
[59.574 56.176 54.902 ... 49.86  51.95  52.942]
[58.54  49.806 54.899 ... 47.497 48.741 49.645]
[67.629 54.254 65.152 ... 56.34  56.654 57.38 ]
[50.941 38.476 48.422 ... 39.638 40.047 40.803]
[47.239 36.319 44.356 ... 35.933 36.654 37.475]
[51.14  38.478 48.677 ... 39.845 40.21  40.956]
[84.729 72.232 81.829 ... 73.416 73.997 74.776]
[67.304 66.842 62.205 ... 58.79  61.232 62.226]
[62.529 51.56  59.393 ... 51.257 52.082 52.915]
[69.192 61.186 65.269 ... 58.337 59.748 60.674]
[55.89  45.593 52.671 ... 44.648 45.573 46.427]
[61.523 54.001 57.576 ... 50.716 52.186 

[49.45  59.965 44.235 ... 47.292 50.289 51.022]
[51.61  59.687 46.217 ... 47.651 50.643 51.475]
[52.853 59.998 47.432 ... 48.273 51.242 52.105]
[56.788 62.923 51.359 ... 51.601 54.532 55.426]
[52.195 60.034 46.794 ... 48.077 51.064 51.905]
[53.041 60.259 47.623 ... 48.511 51.483 52.344]
[51.278 59.803 45.906 ... 47.632 50.631 51.447]
[59.18  66.28  53.764 ... 54.633 57.598 58.466]
[68.825 72.438 63.432 ... 62.289 65.078 66.029]
[74.921 80.346 69.492 ... 69.456 72.348 73.264]
[90.379 93.092 84.998 ... 83.517 86.238 87.205]
[56.059 59.31  50.708 ... 49.191 51.96  52.916]
[63.445 65.594 58.139 ... 56.096 58.779 59.752]
[74.128 75.742 68.83  ... 66.615 69.252 70.232]
[70.425 77.359 65.015 ... 65.858 68.814 69.69 ]
[63.793 67.723 58.396 ... 57.383 60.194 61.139]
[93.151 97.616 87.724 ... 87.237 90.073 91.011]
[1861.211 1843.848 1864.177 ... 1856.607 1854.077 1853.762]
[55.676 60.977 50.253 ... 49.965 52.859 53.773]
[71.39  75.767 65.972 ... 65.296 68.132 69.07 ]
[54.438 60.306 49.009 ... 49

[11.484  9.609 11.447 ...  3.712  0.716  0.758]
[10.586 10.137 10.684 ...  3.687  0.974  0.223]
[12.022  9.223 11.965 ...  3.94   1.092  1.274]
[ 9.841 10.157 10.427 ...  4.512  2.04   1.111]
[14.528 12.898 12.423 ...  3.213  4.775  5.772]
[ 8.889 11.292  9.286 ...  4.168  2.475  1.867]
[10.122 10.18  10.481 ...  4.115  1.579  0.683]
[ 9.419  9.502 11.512 ...  7.45   4.909  3.913]
[ 9.259  9.654 11.479 ...  7.664  5.165  4.17 ]
[10.778  9.803 10.988 ...  3.968  1.109  0.136]
[10.455 10.192 10.593 ...  3.739  1.096  0.316]
[10.768 12.569  9.382 ...  0.853  2.334  3.069]
[11.316 13.062  9.538 ...  0.     3.005  3.833]
[11.255 10.297 10.928 ...  3.005  0.     0.997]
[10.755  9.916 10.903 ...  3.833  0.997  0.   ]


用dataframe將row合併

In [7]:
import pandas as pd

res = pd.DataFrame()

for d in range(1923):
    
    df1 = pd.DataFrame(np.array(place_list[d]).reshape(1,len(place_list[d])),columns=[list(range(1923))])
    
    res=res.append(df1,ignore_index='True')
    

    


In [127]:
res

0       1       2       3       4       5       6       7       8     \
0      0.000  18.913   5.430  41.890   4.866   0.136  18.441  40.528  41.370   
1     18.913   0.000  20.545  33.711  22.342  19.048   1.112  40.861  25.509   
2      5.430  20.545   0.000  38.455   2.719   5.410  19.823  35.562  40.291   
3     41.890  33.711  38.455   0.000  41.139  41.975  32.847  18.288  19.440   
4      4.866  22.342   2.719  41.139   0.000   4.781  21.702  37.745  42.873   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1918  10.455  10.192  10.593  33.096  12.720  10.580   9.359  35.443  30.921   
1919  10.768  12.569   9.382  31.479  11.862  10.874  11.626  32.772  31.045   
1920  11.316  13.062   9.538  30.781  12.097  11.417  12.087  31.919  30.776   
1921  11.255  10.297  10.928  32.010  13.193  11.376   9.388  34.436  30.128   
1922  10.755   9.916  10.903  32.919  13.036  10.881   9.073  35.426  30.626   

        9     ...    1913    1914    1915    1916    1917    1918    1919  \
0     51.717  ...   8.889  10.122   9.419   9.259  10.778  10.455  10.768   
1     44.270  ...  11.292  10.180   9.502   9.654   9.803  10.192  12.569   
2     47.892  ...   9.286  10.481  11.512  11.479  10.988  10.593   9.382   
3     10.565  ...  34.372  33.574  36.588  36.869  32.986  33.096  31.479   
4     50.512  ...  11.291  12.539  12.995  12.911  13.104  12.720  11.862   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
1918  43.374  ...   1.566   0.483   3.859   4.105   0.397   0.000   2.944   
1919  41.578  ...   3.317   3.295   6.605   6.816   3.205   2.944   0.000   
1920  40.839  ...   4.168   4.115   7.450   7.664   3.968   3.739   0.853   
1921  42.281  ...   2.475   1.579   4.909   5.165   1.109   1.096   2.334   
1922  43.215  ...   1.867   0.683   3.913   4.170   0.136   0.316   3.069   

        1920    1921    1922  
0     11.316  11.255  10.755  
1     13.062  10.297   9.916  
2      9.538  10.928  10.903  
3     30.781  32.010  32.919  
4     12.097  13.193  13.036  
...      ...     ...     ...  
1918   3.739   1.096   0.316  
1919   0.853   2.334   3.069  
1920   0.000   3.005   3.833  
1921   3.005   0.000   0.997  
1922   3.833   0.997   0.000  

[1923 rows x 1923 columns]